export const ADD_TODO = "ADD_TODO"
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS"
export const FETCH_TODOS_PENDING = "FETCH_TODOS_PENDING"
export const FETCH_TODOS_ERROR = "FETCH_TODOS_ERROR"